on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: deta
          POSTGRES_PASSWORD: deta
          POSTGRES_DATABASE: deta
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.3
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'regular'
        version: '7.5'
    - run: raco pkg install --auto --batch deta-lib/ deta-doc/ deta-test/
    - run: raco test -j 4 deta-lib/ deta-test/
      env:
        DETA_POSTGRES_DB: deta
        DETA_POSTGRES_USER: deta
        DETA_POSTGRES_PASS: deta
    - run: bash ci/docs.sh
      env:
        DETA_DOCS_DEPLOY_KEY_PASSPHRASE: ${{ secrets.DETA_DOCS_DEPLOY_KEY_PASSPHRASE }}
        DETA_DOCS_SSH_HOST: ${{ secrets.DETA_DOCS_SSH_HOST }}
        DETA_DOCS_SSH_PORT: ${{ secrets.DETA_DOCS_SSH_PORT }}
